version: "3.9"
services:
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - "./app:/var/www/html"
      - "./config/php/fpm.config:/etc/php81/php-fpm.d/www.conf"
    networks:
      - appnet

  nginx:
    container_name: nginx-server
    build:
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - '8800:80'
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - appnet

  mysql:
    container_name: mysql-server
    build:
      dockerfile: docker/mysql/Dockerfile
    ports: 
      - '3306:3306'
    volumes:
      - "./storage/mysql_base:/var/lib/mysql"
    networks:
      - appnet

networks:
  appnet:
    

    