version: "3.9"
services:
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 8088:80
    volumes:
      - "./app/:/var/www/html"
      - "./config/php/fpm.config:/etc/php81/php-fpm.d/www.conf"
      - "./config/php/httpd.conf:/etc/apache2/httpd.conf"
    networks:
      - appnet

  nginx:
    container_name: nginx-server
    build:
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - '8800:80'
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - appnet

  mysql:
    env_file:
    - ./.env
    container_name: mysql-db
    image: mysql:latest
    ports: 
      - '3306:3306'
    volumes:
      - "./storage/mysql-db:/var/lib/mysql"
    networks:
      - appnet

networks:
  appnet:
    

    