version: "3.9"
services:
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - "./app:/var/www/html"
      - "./config/php/fpm.config:/etc/php81/php-fpm.d/www.conf"
    networks:
      - appnet

  nginx:
    container_name: nginx-server
    build:
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - '8800:80'
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - appnet

  mysql:
    container_name: mysql-db
    image: mysql:latest
    volumes:
      - "./storage/mysql-db:/var/lib/mysql"
    environment: 
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass' 
    networks:
      - appnet

networks:
  appnet:
    

    